public class Simulacao{
    Run|Debug
    public static void main(String[] args){
        Carro opala = new Carro();
        opala.velocidade = 0;
        oplaca.placa = "ACLR300";
        opala.modelo = "Comodoro";
        opala.ano = 76;

        Radar radar = new Radar();
        radar.modelo = "pardal";
        radar.limiteVelocidade = 60;
        radar.localizacao = "Pistão Sul";

        opala.acelerar(); // 5
        opala.acelerar(); // 10
        opala.acelerar(); // 15
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar();
        opala.acelerar(); // 60

        radar.
    }
}